New Documentation
TGlas/tscript pull request #83
Opened 2021-07-06 09:42 UTC by duckmopsi

Revised the old documentation and added or changed examples.

2021-07-06 10:57 UTC, TGlas requested changes
Thanks! I went through it and added a number of remarks. Some are minor. The most important structural change is to include the images as data URIs.

2021-07-06 10:57 UTC, TGlas commented on src/doc/errors.ts
> +			must be unique, it cannot be overloaded. This is explicitely different from other
typo: explicitely -> explicitly

2021-07-06 10:57 UTC, TGlas commented on src/doc/errors.ts
> +            languages Remove all but one constructor
Point (period) missing after "languages".

2021-07-06 10:57 UTC, TGlas commented on src/doc/errors.ts
> +    if (a<=b) then return -1;
Remove parentheses, otherwise this is a C-style if statement. Same comment refers to the similar if-statements below.

2021-07-06 10:57 UTC, TGlas commented on src/doc/errors.ts
> +if (not ... ) then
Remove parentheses (again)

2021-07-06 10:57 UTC, TGlas commented on src/doc/errors.ts
> +        if (i >= arr.size())
remove parentheses...

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +var a = 1;
Better example: var a = [1,2,3];
and of course the same for d. Then the second test case will print false.

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +if (confirmed) then print("Hello World");       # if user confirms, the program prints "Hello World", else nothing
remove parentheses: if confirmed then ...

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +print(s);                                       # prints the input given by the user
Handle s == null, which happens when the user cancels?

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +        All trigonometric functions work with Radian.
"Radian" -> "radians"

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +turtle.pen(true);           # lift the pen down
"lift" always goes with "up". Maybe "lower the pen"?

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +canvas.setLineColor(1,0,0);                                         # sets the Linecolor to red
"Linecolor" --> "line color"

2021-07-06 10:57 UTC, TGlas commented on src/doc/concepts.ts
> +        <img src="images/arrays.png"/>
I cannot see the "images" folder, did you forget to `git add`? Also, including external images would disallow distributing the whole IDE as a single file. Please convert the images to data URIs with [a tool like this](https://onlinepngtools.com/convert-png-to-data-uri).

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +			<tscript do-not-run>
Not sure from the context displayed in the preview: should this really be a tscript tag or better an ebnf tag?

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +        # constructor() {                             # standard constructor, gets called by "var c = Circle()" and sets m_radius by default to 1
Not sure if a commented constructor is helpful. Instead, use a default value for the radius?

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +var inf = Real.inf();           # sets inf to Infinite
Infinite --> Infinity
Better: sets the variable inf to mathematical infinity

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +var nan = Real.nan();           # sets nan to NaN
comment: sets the variable nan to the special constant NaN (not-a-number)

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +print(3.5 - 2.5);               # prints 1.0
No, it prints `1`. Also, `print(1.0);` prints `1`. The output is not marked explicitly as a real, since it is for the user, not for the programmer.

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +print(4 / 2);                   # prints 2.0
Same as above: it prints `2`, not `2.0`.

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +print(4^0.5);               # prints 2.0
2, not 2.0

2021-07-06 10:57 UTC, TGlas commented on src/doc/language.ts
> +if (example == null) then print("example");     # prints "example"
drop superfluous parenthesis in the if clauses

2021-07-06 10:57 UTC, TGlas commented on src/doc/stdlib.ts
> +print(b);               # prints [0, 1, 2, 3], since it's a reference
maybe: "since it's a reference to the same array also referenced by variable a"

2021-07-07 14:48 UTC, TGlas commented
I tried the PR. I had to merge manually, but that was not a big deal. I arrived at the following two problems:

- There are still two references to not-yet-embedded images in `tscript/src/doc/ide.ts`.
- Line 3 in tgui.ts should read `import { doc_legal } from "../doc/legal";` - i.e., refer to the renamed file.

2021-07-07 15:57 UTC, Jartreg commented
@duckmopsi if you haven't noticed yet, there are a lot of conflicts in your branch that prevent it from being merged. You should resolve them by rebasing your branch onto the current master.

I don't know how comfortable you are with git, so I might be telling you things you already know, but in case, here's a short description of what happened:

<details>
<summary>Conflicts</summary>

You started your branch a while ago and modified some files. In the meanwhile, *the same files* have been modified on the `master` branch. Now that we want to merge your changes onto the `master` branch, git doesn't know what to do with the parts of the code that were modified by you **and on `master`**.

You can see that the code in your branch is based on code from back in February:

![snippet of a branch graph](https://user-images.githubusercontent.com/28811733/124788207-71377a80-df49-11eb-9e8d-bc597da75af2.png)

In the meanwhile, there have been changes to the exact files you are modifying:

![changes in commit ed3eab21](https://user-images.githubusercontent.com/28811733/124789089-400b7a00-df4a-11eb-85f0-9f1d7dd3fc40.png)

These changes are causing the conflicts.

</details>

<details>
<summary>Rebasing</summary>

By rebasing your branch onto master, you make sure that all these changes are included in your branch as well. An alternative would be to merge master into your branch, but its equally as tedious and yields ugly results because of additional commits.

Rebasing basically takes your junction point from February and puts it after the current changes. While git is doing that, you just need to resolve the conflicts that git cannot solve by itself.

To start the rebase, you can use `git rebase master` and follow the instructions or use a git GUI of your choice to make the process easier. After you are done, you need to push the changes with `git push --force`.

Here are some resources that could help you:
* [GitHub Docs: Using Git rebase](https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line)
* [GitHub Docs: Resolving conflicts after rebase](https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase)
* [GitLab Docs: Introduction to Git rebase, force-push, and merge conflicts](https://docs.gitlab.com/ee/topics/git/git_rebase.html)

Feel free to ask if you run into more trouble.

</details>

(Psst... While you're at it, you could try to change commit messages like "last commit" to [something more meaningfull](https://chris.beams.io/posts/git-commit/))

2021-07-15 07:47 UTC, TGlas approved these changes

2021-07-15 07:52 UTC, merged